export const mockItineraryData = {
  days: [
    {
      date: "2024-01-15",
      activities: [
        {
          time: "09:00",
          duration: "2 hours",
          name: "Metropolitan Museum of Art",
          location: "1000 5th Ave, New York, NY",
          description: "Explore world-class art collections and exhibitions",
          cost: 25,
          entryFee: 25,
          weather: "Sunny, 22°C",
          transport: "Subway",
          transportCost: 3,
          image: "/placeholder.svg?height=200&width=300",
          category: "cultural",
          events: [{ name: "Special Egyptian Art Exhibition", time: "10:00 - 16:00" }],
        },
        {
          time: "12:00",
          duration: "1 hour",
          name: "Central Park Lunch",
          location: "Central Park, New York, NY",
          description: "Relaxing lunch break in the heart of Manhattan",
          cost: 15,
          weather: "Sunny, 24°C",
          transport: "Walking",
          transportCost: 0,
          image: "/placeholder.svg?height=200&width=300",
          category: "relaxation",
        },
        {
          time: "14:00",
          duration: "3 hours",
          name: "Times Square & Broadway",
          location: "Times Square, New York, NY",
          description: "Experience the energy of NYC's most famous intersection",
          cost: 0,
          weather: "Sunny, 25°C",
          transport: "Subway",
          transportCost: 3,
          image: "/placeholder.svg?height=200&width=300",
          category: "tourist",
          events: [{ name: "Street Performers", time: "All day" }],
        },
        {
          time: "19:00",
          duration: "2 hours",
          name: "Little Italy Dinner",
          location: "Little Italy, New York, NY",
          description: "Authentic Italian cuisine in historic neighborhood",
          cost: 45,
          weather: "Clear, 20°C",
          transport: "Subway",
          transportCost: 3,
          image: "/placeholder.svg?height=200&width=300",
          category: "foodie",
        },
      ],
    },
    {
      date: "2024-01-16",
      activities: [
        {
          time: "10:00",
          duration: "2 hours",
          name: "Statue of Liberty",
          location: "Liberty Island, New York, NY",
          description: "Visit America's symbol of freedom and democracy",
          cost: 23,
          entryFee: 23,
          weather: "Partly cloudy, 21°C",
          transport: "Ferry",
          transportCost: 12,
          image: "/placeholder.svg?height=200&width=300",
          category: "tourist",
        },
        {
          time: "15:00",
          duration: "2 hours",
          name: "Brooklyn Bridge Walk",
          location: "Brooklyn Bridge, New York, NY",
          description: "Scenic walk across the iconic Brooklyn Bridge",
          cost: 0,
          weather: "Partly cloudy, 23°C",
          transport: "Walking",
          transportCost: 0,
          image: "/placeholder.svg?height=200&width=300",
          category: "adventure",
        },
      ],
    },
  ],
  lastUpdated: new Date().toISOString(),
}

export const mockBudgetData = {
  accommodation: 300,
  meals: 180,
  transport: 120,
  activities: 150,
  shopping: 100,
}

export const mockTripsData = [
  {
    id: "1",
    destination: "New York City",
    dates: "Jan 15-17, 2024",
    budget: 850,
    travelStyle: "cultural",
    status: "confirmed",
    ecoFriendly: true,
    createdAt: "2024-01-01",
  },
  {
    id: "2",
    destination: "Paris",
    dates: "Feb 20-25, 2024",
    budget: 1200,
    travelStyle: "foodie",
    status: "draft",
    ecoFriendly: false,
    createdAt: "2024-01-10",
  },
  {
    id: "3",
    destination: "Tokyo",
    dates: "Mar 10-15, 2024",
    budget: 1500,
    travelStyle: "adventure",
    status: "confirmed",
    ecoFriendly: true,
    createdAt: "2024-01-15",
  },
]

export const mockHotelsData = [
  // Budget Hotels
  {
    id: "1",
    name: "Downtown Backpackers Hostel",
    tier: "budget",
    location: "Manhattan, New York",
    pricePerNight: 45,
    rating: 4.2,
    description: "Clean, safe hostel in the heart of Manhattan with free WiFi and continental breakfast.",
    amenities: ["wifi", "restaurant", "parking"],
    images: ["/placeholder.svg?height=200&width=400"],
    ecoFriendly: true,
    specialOffers: ["Free breakfast included", "10% off for stays over 3 nights"],
  },
  {
    id: "2",
    name: "City Center Budget Inn",
    tier: "budget",
    location: "Midtown, New York",
    pricePerNight: 65,
    rating: 4.0,
    description: "Affordable accommodation with modern amenities and great location.",
    amenities: ["wifi", "gym"],
    images: ["/placeholder.svg?height=200&width=400"],
    ecoFriendly: false,
    specialOffers: ["Early bird discount available"],
  },
  {
    id: "3",
    name: "Brooklyn Heights Hostel",
    tier: "budget",
    location: "Brooklyn, New York",
    pricePerNight: 38,
    rating: 4.3,
    description: "Trendy hostel with stunning Manhattan views and vibrant social atmosphere.",
    amenities: ["wifi", "restaurant"],
    images: ["/placeholder.svg?height=200&width=400"],
    ecoFriendly: true,
    specialOffers: ["Free walking tour included"],
  },

  // Mid-range Hotels
  {
    id: "4",
    name: "Manhattan Comfort Hotel",
    tier: "mid-range",
    location: "Upper East Side, New York",
    pricePerNight: 125,
    rating: 4.5,
    description: "Comfortable hotel with excellent service and convenient location near Central Park.",
    amenities: ["wifi", "gym", "restaurant", "parking"],
    images: ["/placeholder.svg?height=200&width=400"],
    ecoFriendly: true,
    specialOffers: ["Complimentary room upgrade subject to availability"],
  },
  {
    id: "5",
    name: "Times Square Boutique Hotel",
    tier: "mid-range",
    location: "Times Square, New York",
    pricePerNight: 145,
    rating: 4.4,
    description: "Stylish boutique hotel in the heart of Times Square with modern amenities.",
    amenities: ["wifi", "gym", "restaurant", "spa"],
    images: ["/placeholder.svg?height=200&width=400"],
    ecoFriendly: false,
    specialOffers: ["Broadway show package available"],
  },
  {
    id: "6",
    name: "SoHo Design Hotel",
    tier: "mid-range",
    location: "SoHo, New York",
    pricePerNight: 165,
    rating: 4.6,
    description: "Contemporary design hotel in trendy SoHo with artistic flair and premium amenities.",
    amenities: ["wifi", "gym", "restaurant", "spa", "parking"],
    images: ["/placeholder.svg?height=200&width=400"],
    ecoFriendly: true,
    specialOffers: ["Art gallery tour included", "Late checkout available"],
  },

  // Luxury Hotels
  {
    id: "7",
    name: "The Plaza New York",
    tier: "luxury",
    location: "Fifth Avenue, New York",
    pricePerNight: 450,
    rating: 4.8,
    description: "Iconic luxury hotel offering unparalleled elegance and world-class service since 1907.",
    amenities: ["wifi", "gym", "restaurant", "spa", "pool", "parking"],
    images: ["/placeholder.svg?height=200&width=400"],
    ecoFriendly: false,
    specialOffers: ["Champagne welcome", "Luxury spa package"],
  },
  {
    id: "8",
    name: "The St. Regis New York",
    tier: "luxury",
    location: "Midtown Manhattan, New York",
    pricePerNight: 520,
    rating: 4.9,
    description: "Timeless luxury with bespoke butler service and exquisite accommodations.",
    amenities: ["wifi", "gym", "restaurant", "spa", "parking"],
    images: ["/placeholder.svg?height=200&width=400"],
    ecoFriendly: true,
    specialOffers: ["Butler service included", "Michelin-starred dining"],
  },
  {
    id: "9",
    name: "The Carlyle, A Rosewood Hotel",
    tier: "luxury",
    location: "Upper East Side, New York",
    pricePerNight: 380,
    rating: 4.7,
    description: "Sophisticated luxury hotel with timeless elegance and personalized service.",
    amenities: ["wifi", "gym", "restaurant", "spa", "pool"],
    images: ["/placeholder.svg?height=200&width=400"],
    ecoFriendly: true,
    specialOffers: ["Afternoon tea service", "Central Park view rooms"],
  },
  
]
export const mockCityGuideData ={
  visaInfo: "Most tourists can obtain a visa on arrival for 30 days. Ensure your passport is valid for at least 6 months.",
  publicTransportTips: "Use metro cards for discounted rates. Local buses and metros are reliable and affordable.",
  localCustoms: "Always remove your shoes when entering temples. Tipping is not mandatory but appreciated.",
  localEvents: [
    "June: Summer Music Festival",
    "July: Local Food Fair",
    "August: Independence Day Parade",
  ],
  ecoFriendlySuggestions: "Consider renting bicycles or using electric scooters for local travel. Participate in eco-tours and support local green initiatives."
}

