export const mockItineraryData = {
  days: [
    {
      date: "2024-01-15",
      activities: [
        {
          time: "09:00",
          duration: "2 hours",
          name: "Metropolitan Museum of Art",
          location: "1000 5th Ave, New York, NY",
          description: "Explore world-class art collections and exhibitions",
          cost: 25,
          entryFee: 25,
          weather: "Sunny, 22°C",
          transport: "Subway",
          transportCost: 3,
          image: "/placeholder.svg?height=200&width=300",
          category: "cultural",
          events: [{ name: "Special Egyptian Art Exhibition", time: "10:00 - 16:00" }],
        },
        {
          time: "12:00",
          duration: "1 hour",
          name: "Central Park Lunch",
          location: "Central Park, New York, NY",
          description: "Relaxing lunch break in the heart of Manhattan",
          cost: 15,
          weather: "Sunny, 24°C",
          transport: "Walking",
          transportCost: 0,
          image: "/placeholder.svg?height=200&width=300",
          category: "relaxation",
        },
        {
          time: "14:00",
          duration: "3 hours",
          name: "Times Square & Broadway",
          location: "Times Square, New York, NY",
          description: "Experience the energy of NYC's most famous intersection",
          cost: 0,
          weather: "Sunny, 25°C",
          transport: "Subway",
          transportCost: 3,
          image: "/placeholder.svg?height=200&width=300",
          category: "tourist",
          events: [{ name: "Street Performers", time: "All day" }],
        },
        {
          time: "19:00",
          duration: "2 hours",
          name: "Little Italy Dinner",
          location: "Little Italy, New York, NY",
          description: "Authentic Italian cuisine in historic neighborhood",
          cost: 45,
          weather: "Clear, 20°C",
          transport: "Subway",
          transportCost: 3,
          image: "/placeholder.svg?height=200&width=300",
          category: "foodie",
        },
      ],
    },
    {
      date: "2024-01-16",
      activities: [
        {
          time: "10:00",
          duration: "2 hours",
          name: "Statue of Liberty",
          location: "Liberty Island, New York, NY",
          description: "Visit America's symbol of freedom and democracy",
          cost: 23,
          entryFee: 23,
          weather: "Partly cloudy, 21°C",
          transport: "Ferry",
          transportCost: 12,
          image: "/placeholder.svg?height=200&width=300",
          category: "tourist",
        },
        {
          time: "15:00",
          duration: "2 hours",
          name: "Brooklyn Bridge Walk",
          location: "Brooklyn Bridge, New York, NY",
          description: "Scenic walk across the iconic Brooklyn Bridge",
          cost: 0,
          weather: "Partly cloudy, 23°C",
          transport: "Walking",
          transportCost: 0,
          image: "/placeholder.svg?height=200&width=300",
          category: "adventure",
        },
      ],
    },
  ],
  lastUpdated: new Date().toISOString(),
}

export const mockBudgetData = {
  accommodation: 300,
  meals: 180,
  transport: 120,
  activities: 150,
  shopping: 100,
}

export const mockTripsData = [
  {
    id: "1",
    destination: "New York City",
    dates: "Jan 15-17, 2024",
    budget: 850,
    travelStyle: "cultural",
    status: "confirmed",
    ecoFriendly: true,
    createdAt: "2024-01-01",
  },
  {
    id: "2",
    destination: "Paris",
    dates: "Feb 20-25, 2024",
    budget: 1200,
    travelStyle: "foodie",
    status: "draft",
    ecoFriendly: false,
    createdAt: "2024-01-10",
  },
  {
    id: "3",
    destination: "Tokyo",
    dates: "Mar 10-15, 2024",
    budget: 1500,
    travelStyle: "adventure",
    status: "confirmed",
    ecoFriendly: true,
    createdAt: "2024-01-15",
  },
]
